"""include drop column for url 

Revision ID: 39d4d8a959ab
Revises: aa05d09625d6
Create Date: 2025-11-28 10:19:45.302390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39d4d8a959ab'
down_revision: Union[str, Sequence[str], None] = 'aa05d09625d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'audio_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('audio_url', sa.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
