"""accepting arabic content in messages content

Revision ID: 70ae28f1dcfd
Revises: 39d4d8a959ab
Create Date: 2025-11-29 09:27:18.779723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ae28f1dcfd'
down_revision: Union[str, Sequence[str], None] = '39d4d8a959ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
